// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simplified_cloud_job_execution_backend.Infrastructure.Database;

#nullable disable

namespace simplified_cloud_job_execution_backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621065801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("simplified_cloud_job_execution_backend.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BillingProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("billing_processed");

                    b.Property<string>("ComputeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compute_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditCost")
                        .HasColumnType("numeric")
                        .HasColumnName("credit_cost");

                    b.Property<double?>("ExecutionDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("execution_duration_seconds");

                    b.Property<string>("InputFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_file_name");

                    b.Property<string>("InputFileReference")
                        .HasColumnType("text")
                        .HasColumnName("input_file_reference");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_name");

                    b.Property<string>("OutputFileReference")
                        .HasColumnType("text")
                        .HasColumnName("output_file_reference");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.ToTable("Jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
