// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using simplified_cloud_job_execution_backend.Infrastructure.Database;

#nullable disable

namespace simplified_cloud_job_execution_backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622011753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("simplified_cloud_job_execution_backend.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BillingProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("billing_processed");

                    b.Property<string>("ComputeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compute_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditCost")
                        .HasColumnType("numeric")
                        .HasColumnName("credit_cost");

                    b.Property<double?>("ExecutionDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("execution_duration_seconds");

                    b.Property<string>("InputFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_file_name");

                    b.Property<string>("InputFileReference")
                        .HasColumnType("text")
                        .HasColumnName("input_file_reference");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_name");

                    b.Property<string>("OutputFileReference")
                        .HasColumnType("text")
                        .HasColumnName("output_file_reference");

                    b.Property<Guid>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_jobs_project_id");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("simplified_cloud_job_execution_backend.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a3e8f89-0fd2-4f42-84c5-2b4a4aa232c1"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GPU-backed model inference and validation workloads.",
                            IsDeleted = false,
                            ProjectName = "Inference Lab"
                        },
                        new
                        {
                            Id = new Guid("af23b61d-4d7e-4f58-9f38-6ccaf68fca74"),
                            CreatedAt = new DateTime(2026, 2, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Batch ETL and analytics exports for engineering metrics.",
                            IsDeleted = false,
                            ProjectName = "Analytics Pipeline"
                        },
                        new
                        {
                            Id = new Guid("d41f4b5a-5c8a-4dbe-a5d6-8f3a923b0d57"),
                            CreatedAt = new DateTime(2026, 3, 15, 12, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Video and media rendering jobs for quality checks.",
                            IsDeleted = false,
                            ProjectName = "Media Rendering"
                        },
                        new
                        {
                            Id = new Guid("f9e8b0a0-1c47-4472-bc7a-2e8e473cd8af"),
                            CreatedAt = new DateTime(2026, 4, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sensor aggregation and device telemetry processing.",
                            IsDeleted = false,
                            ProjectName = "IoT Batch Jobs"
                        },
                        new
                        {
                            Id = new Guid("3c9b2b6d-2a71-4023-8f9d-ea1b48a61520"),
                            CreatedAt = new DateTime(2026, 5, 5, 14, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Model training and hyperparameter sweep workloads.",
                            IsDeleted = false,
                            ProjectName = "ML Training"
                        });
                });

            modelBuilder.Entity("simplified_cloud_job_execution_backend.Domain.Jobs.Job", b =>
                {
                    b.HasOne("simplified_cloud_job_execution_backend.Domain.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_projects_project_id");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
